"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import environ
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"


# Both default to plain localhost so `manage.py runserver` keeps
# working out of the box; set ALLOWED_HOSTS / CSRF_TRUSTED_ORIGINS in
# .env (comma-separated) to whatever host you actually browse the app
# from - a LAN IP, a custom port, a devcontainer/tunnel URL, a real
# domain - or Django will reject login (DisallowedHost / a CSRF
# "Referer checking failed" error) for anything not listed here.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS", "http://localhost:8000,http://127.0.0.1:8000"
    ).split(",")
    if origin.strip()
]

# Session/cookie hardening - Secure/SSL-redirect flags are conditioned
# on DEBUG the same way the rest of this file already branches (see
# ALLOWED_HOSTS/CSRF_TRUSTED_ORIGINS above): `manage.py runserver`
# during local dev is plain HTTP, so a hardcoded *_COOKIE_SECURE=True
# would silently break every login/CSRF-protected POST there. A real
# deployment (DEBUG=False) is expected to terminate HTTPS, so these
# flip on automatically without a separate env var to remember to set.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days, if the browser stays open that long

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # required for pgvector.django.HnswIndex - see ChunkEmbedding.Meta.indexes
    'RAG'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'RAG.middleware.RequestTraceMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'RAG.middleware.RoleBasedAccessMiddleware',
    'RAG.middleware.SystemConfigSyncMiddleware',
    'RAG.middleware.RequestActivityMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'RAG.context_processors.sidebar_status',
                'RAG.context_processors.breadcrumbs',
            ],
        },
    },
]
LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"
WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": env("DB_NAME"),

        "USER": env("DB_USER"),

        "PASSWORD": env("DB_PASSWORD"),

        "HOST": env("DB_HOST"),

        "PORT": env("DB_PORT"),

        # Without this, Django opens a fresh PostgreSQL connection
        # (full TCP + auth handshake) on every single HTTP request and
        # tears it down at the end - CONN_MAX_AGE keeps connections
        # open and reused across requests instead. CONN_HEALTH_CHECKS
        # (Django 4+) validates a reused connection isn't stale before
        # handing it back out, so this stays safe across a Postgres
        # restart/network blip rather than just being a raw perf flag.
        "CONN_MAX_AGE": env.int("CONN_MAX_AGE", default=60),

        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

TOP_K = int(os.getenv("TOP_K", 3))

EMBEDDING_MODEL = os.getenv(
    "EMBEDDING_MODEL",
    "all-MiniLM-L6-v2"
)
EMBEDDING_DIMENSION = 384


# ==========================================
# Document Validation
# ==========================================

ALLOWED_FILE_EXTENSIONS = [
    ".pdf",
    ".docx",
    ".txt",
]

MAX_FILE_SIZE = 20 * 1024 * 1024   # 20 MB

# Not env-driven (a stray `CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", 500))`
# used to sit near the top of this file and was unconditionally
# overwritten here two lines later - the env var had zero effect, ever;
# removed rather than fixed, since CHUNK_SIZE stopped being this app's
# real source of truth the moment SystemConfiguration.chunk_size shipped
# (RAG/services/system_config_service.py) - this literal is only the
# seed value get_config() uses the very first time that DB row is
# created, and admin/settings.html is the actual live control from then
# on. CHUNK_OVERLAP is a plain hardcoded constant for the same reason -
# see system_config_service.MANAGED_SETTINGS_FIELDS.
CHUNK_SIZE = 800

CHUNK_OVERLAP = 150

# ==========================================
# Advanced Retrieval (Sprint 6)
# ==========================================
# Query expansion, HyDE, and multi-query retrieval each cost at least
# one extra Gemini call per question on top of the existing hybrid
# pipeline, so they default OFF - flip them on per-deployment via
# .env once the added latency/cost is acceptable. Metadata filtering
# is opt-in per-call (a `filters=None` param), so it needs no flag.
# Dynamic top-k is local/free (no LLM call) and defaults ON.

ENABLE_QUERY_EXPANSION = os.getenv("ENABLE_QUERY_EXPANSION", "False") == "True"

ENABLE_HYDE = os.getenv("ENABLE_HYDE", "False") == "True"

ENABLE_MULTI_QUERY = os.getenv("ENABLE_MULTI_QUERY", "False") == "True"

ENABLE_DYNAMIC_TOP_K = os.getenv("ENABLE_DYNAMIC_TOP_K", "True") == "True"

DYNAMIC_TOP_K_MAX = int(os.getenv("DYNAMIC_TOP_K_MAX", 10))

MULTI_QUERY_VARIANTS = int(os.getenv("MULTI_QUERY_VARIANTS", 3))

# ==========================================
# Reranking (Sprint 7)
# ==========================================
# BGE Reranker re-scores merged candidate chunks with a cross-encoder
# pass over (question, chunk) pairs - a stronger relevance signal than
# the independent per-chunk scores hybrid retrieval already attaches.
# It costs a local model inference pass per question (no extra Gemini
# call, no new dependency - see reranker_service.py), but still adds
# latency and a one-time model load, so it defaults OFF like the
# Sprint 6 LLM-cost features - flip it on per-deployment via .env.

ENABLE_RERANKER = os.getenv("ENABLE_RERANKER", "False") == "True"

RERANKER_MODEL = os.getenv("RERANKER_MODEL", "BAAI/bge-reranker-base")

# When reranking is enabled, retrieve_chunks() over-fetches this many
# times the effective top-k from each source before reranking, so the
# reranker has a real candidate pool to reorder rather than just
# re-scoring an already-truncated list.
RERANKER_CANDIDATE_MULTIPLIER = int(os.getenv("RERANKER_CANDIDATE_MULTIPLIER", 3))

# ==========================================
# Context Compression (Sprint 8)
# ==========================================
# Hybrid retrieval (especially with HyDE/multi-query/reranking
# enabled) can surface near-duplicate chunks - the same fact
# paraphrased, or overlapping chunks from CHUNK_OVERLAP - that pad the
# LLM's context without adding information. Compression removes
# chunks that are semantically redundant with one already kept (see
# context_compression_service.py), reusing the existing embedding
# model - no new dependency, no LLM call. Off by default: an overly
# aggressive threshold could drop a chunk that genuinely mattered, so
# this should be enabled deliberately per-deployment via .env.

ENABLE_CONTEXT_COMPRESSION = os.getenv("ENABLE_CONTEXT_COMPRESSION", "False") == "True"

CONTEXT_COMPRESSION_THRESHOLD = float(os.getenv("CONTEXT_COMPRESSION_THRESHOLD", 0.92))

# How long (seconds) the retrieval-side caches stay warm: the full
# retrieve_chunks() result for a repeated question, the per-accessible-
# scope BM25 index, and the per-accessible-scope visible-entity set for
# graph retrieval (see retrieval_service.py / bm25_service.py /
# graph_retrieval_service.py). Short and shared across all three on
# purpose - the correctness risk they bound is the same (a document
# uploaded/embedded moments ago not showing up yet), so one knob is
# simpler than three, and short keeps that window tight.
RETRIEVAL_CACHE_TTL = int(os.getenv("RETRIEVAL_CACHE_TTL", 120))

# Defensive cap on the numbered context string sent to the LLM
# (citation_service.build_cited_context()). Not a real latency fix -
# a live benchmark during the performance audit showed even a trivial
# few-word prompt taking just as long on OpenRouter's free tier, so
# prompt size isn't the actual driver of answer latency here - this is
# a safety net for a pathological large-top_k + compression-disabled
# combination blowing up the prompt, not something normal usage hits.
MAX_CONTEXT_CHARS = int(os.getenv("MAX_CONTEXT_CHARS", 12000))

# ==========================================
# Answer Generation (Sprint 9)
# ==========================================
# Prompt templates, grounding/citation rules, and the "not found"
# fallback text live in prompt_templates.py / citation_service.py.
# ANSWER_TEMPERATURE lowers Gemini's sampling temperature below the
# provider default, so the model sticks closer to the cited sources
# instead of improvising - a direct hallucination-reduction lever.
# Applied unconditionally (not feature-flagged): it costs nothing
# extra and is a generation-quality default for this sprint, not an
# opt-in.

ANSWER_TEMPERATURE = float(os.getenv("ANSWER_TEMPERATURE", 0.2))

# ==========================================
# Background Task Execution (free-tier refactor)
# ==========================================
# Document processing and AI Tasks used to require a separate Celery
# worker process talking to a Redis broker - a hard requirement most
# free-tier hosts (Render free, Railway, Fly.io free allowance,
# PythonAnywhere) don't support, since they only run a single always-on
# process. Both now dispatch onto an in-process
# concurrent.futures.ThreadPoolExecutor instead (see
# RAG/services/task_runner.py) - no broker, no second process, no new
# dependency. Django's cache (see CACHES below) also no longer has a
# Redis-backed option; LocMemCache (Django's implicit default) is the
# only cache backend now, which is fine for the short-TTL, non-critical
# caches that use it (sidebar status, BM25/graph/retrieval caches,
# geolocation, system-config sync).

BACKGROUND_WORKER_THREADS = int(os.getenv("BACKGROUND_WORKER_THREADS", 4))

# When False (default), upload_service.upload_document() processes a
# document inline, exactly as every sprint before this one. When True,
# it dispatches RAG.tasks.process_document_task onto the background
# thread pool instead and returns immediately - the request/response
# cycle no longer waits on extraction/chunking/embedding/
# graph-enrichment for large documents.
ENABLE_ASYNC_PROCESSING = os.getenv("ENABLE_ASYNC_PROCESSING", "False") == "True"

# AI Tasks (Enterprise AI Tasks module) ALWAYS dispatch to the
# background thread pool (RAG.tasks.run_ai_task) - independent of
# ENABLE_ASYNC_PROCESSING above, which only governs document upload
# processing. There is no inline/synchronous execution path for an AI
# Task run, since a run can span up to AI_TASKS_MAX_DOCUMENTS documents;
# unlike the old Celery-based design, this has no missing-worker failure
# mode, since the thread pool lives in this same process.
AI_TASKS_MAX_DOCUMENTS = int(os.getenv("AI_TASKS_MAX_DOCUMENTS", "100"))

# ==========================================
# Monitoring (Sprint 10)
# ==========================================
# Activates the logger.info()/logger.exception() calls already
# present throughout RAG/services/*.py (previously relying on
# Django's implicit default, which only surfaces WARNING+ on the root
# logger) with a consistent console format. DJANGO_LOG_LEVEL lets a
# deployment turn up verbosity without a code change.

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        # Stamps every record with the current request's trace id (see
        # RAG.services.trace) so %(trace_id)s below lets a slow/failed
        # Ask AI request's full stage-by-stage log trail be found with
        # one grep, without touching any individual logger.info() call.
        "trace_id": {
            "()": "RAG.services.trace.TraceIdLogFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s [%(trace_id)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["trace_id"],
        },
        # Automatic, app-wide error grouping/dedup (RAG.models.ErrorGroup)
        # - additive alongside "console", not a replacement. WARNING+
        # only: every existing logger.warning()/error()/exception() call
        # across RAG/services/*.py, RAG/views.py, RAG/tasks.py starts
        # flowing into ErrorGroup with zero call-site changes. See
        # RAG.services.error_intelligence_service's module docstring.
        "error_capture": {
            "class": "RAG.services.error_intelligence_service.ErrorCaptureHandler",
            "level": "WARNING",
        },
    },
    "root": {
        "handlers": ["console", "error_capture"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console", "error_capture"],
            "level": os.getenv("DJANGO_FRAMEWORK_LOG_LEVEL", "WARNING"),
            "propagate": False,
        },
        # Chatty third-party HTTP/model-download clients that would
        # otherwise drown out RAG.* logs at INFO - each request the
        # embedding/reranker model libraries make to Hugging Face
        # logs a line by default.
        "httpx": {"level": "WARNING", "propagate": True},
        "httpcore": {"level": "WARNING", "propagate": True},
        "urllib3": {"level": "WARNING", "propagate": True},
    },
}


GEMINI_API_KEY = env(
    "GEMINI_API_KEY",
    default=""
)

# LLM provider selection.
#
# OpenRouter is the default primary provider (a free-tier model) so
# everyday usage doesn't run into Gemini's free-tier quota limits.
# set LLM_PROVIDER=gemini in .env to flip which one is primary.
LLM_PROVIDER = env("LLM_PROVIDER", default="openrouter")

# Whether llm_client.LLMClient is allowed to fall through to another
# configured provider when the primary one fails/times out/rate-limits.
# Defaults OFF: a provider selected in Settings must be the one that
# actually answers, or the request fails with a clear error - never a
# silent, invisible switch to a different provider/model. An admin who
# wants resilience over strict provider fidelity can flip this on from
# Admin > Settings (SystemConfiguration.enable_fallback overrides this
# at runtime, same pattern as every other MANAGED_SETTINGS_FIELDS entry).
LLM_FALLBACK_ENABLED = env.bool("LLM_FALLBACK_ENABLED", default=False)

# Gemini's own model name - kept independent from OPENROUTER_MODEL so
# the Gemini fallback client never gets handed an OpenRouter-style
# model string (e.g. "deepseek/deepseek-chat-v3.1:free").
LLM_MODEL = env("LLM_MODEL", default="gemini-2.0-flash")

OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default="")

# Was "deepseek/deepseek-chat-v3.1:free" - that specific free slug has
# since been retired by OpenRouter (live-verified: returns 404 "This
# model is unavailable for free. The paid version is available now -
# use this slug instead: deepseek/deepseek-chat-v3.1"). Free-tier
# model availability shifts over time; openai/gpt-oss-20b:free is
# live-verified working as of this fix, and - like the other two
# providers' models - changeable from Admin > Settings without a
# redeploy if it's ever retired too. See
# RAG.services.llm_client.PROVIDER_REGISTRY.
OPENROUTER_MODEL = env(
    "OPENROUTER_MODEL",
    default="openai/gpt-oss-20b:free"
)

# Groq - OpenAI-compatible REST API, no SDK dependency (see
# RAG.services.llm_client.GroqClient). llama-3.1-8b-instant is a
# long-standing, small/fast free-tier Groq model - a reasonable
# default; changeable from Admin > Settings like the other two.
GROQ_API_KEY = env("GROQ_API_KEY", default="")
GROQ_MODEL = env("GROQ_MODEL", default="llama-3.1-8b-instant")

# Per-attempt request timeout and per-provider retry count for the LLM
# fallback chain (RAG.services.llm_client.LLMClient) - infra-level
# knobs, env-only (not exposed in Admin > Settings, unlike the
# provider/model choices). Deliberately short: the whole point of the
# fallback chain is to fail fast and move to the next provider rather
# than hang on a slow one.
LLM_REQUEST_TIMEOUT = env.int("LLM_REQUEST_TIMEOUT", default=30)
LLM_MAX_RETRIES = env.int("LLM_MAX_RETRIES", default=1)

SITE_URL = env("SITE_URL", default="")
SITE_NAME = env("SITE_NAME", default="RAG Assistant")